//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserComment
    {
        public int commentid { get; set; }
        public int messageId { get; set; }
        public string commeterId { get; set; }
        public string commentText { get; set; }
    }
}
